version: '2'
services:
  eus:
    image: elastest/eus
    environment:
      - ET_FILES_PATH_IN_HOST=/tmp
      - ET_DATA_IN_HOST=/tmp
      - USE_TORM=false
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
    network_mode: host
